const x = {
    'aliases': [{ 'language': 'zho', 'name': '宝可梦 目标是宝可梦大师' }],
    'averageRuntime': 25,
    'defaultSeasonType': 1,
    'episodes': None,
    'firstAired': '2023-01-13',
    'id': 428456,
    'image': 'https://artworks.thetvdb.com/banners/v4/series/428456/posters/63a19dfc9944f.jpg',
    'isOrderRandomized': False,
    'lastAired': '2023-03-24',
    'lastUpdated': '2025-02-27 16:23:07',
    'name': 'ポケットモンスター めざせポケモンマスター',
    'nameTranslations': ['jpn',
        'eng',
        'zho',
        'pt',
        'spa',
        'ita',
        'pol',
        'deu',
        'rus',
        'fin',
        'nld',
        'fra',
        'kor',
        'por'],
    'nextAired': '',
    'originalCountry': 'jpn',
    'originalLanguage': 'jpn',
    'overview': '放送では、かつて共に旅をしたカスミとタケシのほか、サトシが各地方で強い絆を結びゲットしたポケモンたちが登場。ワクワクと感動がいっぱいの冒険をさらに盛り上げます。',
    'overviewTranslations': ['jpn',
        'eng',
        'zho',
        'pt',
        'ita',
        'pol',
        'rus',
        'fin',
        'nld',
        'fra',
        'por'],
    'score': 3059,
    'slug': 'pokemon-aim-to-be-a-pokemon-master',
    'status': {
        'id': 2,
        'keepUpdated': False,
        'name': 'Ended',
        'recordType': 'series'
    },
    'tvdb_extended': {
        'airsDays': {
            'friday': True,
            'monday': False,
            'saturday': False,
            'sunday': False,
            'thursday': False,
            'tuesday': False,
            'wednesday': False
        },
        'airsTime': '18:45',
        'aliases': [{ 'language': 'zho', 'name': '宝可梦 目标是宝可梦大师' }],
        'artworks': [{
            'height': 1000,
            'id': 63340528,
            'image': 'https://artworks.thetvdb.com/banners/v4/series/428456/posters/63c65a25f3bda.jpg',
            'includesText': True,
            'language': 'jpn',
            'score': 100002,
            'status': { 'id': 0, 'name': None },
            'tagOptions': None,
            'thumbnail': 'https://artworks.thetvdb.com/banners/v4/series/428456/posters/63c65a25f3bda_t.jpg',
            'thumbnailHeight': 0,
            'thumbnailWidth': 0,
            'type': 2,
            'updatedAt': 0,
            'width': 680
        },
        {
            'height': 1080,
            'id': 63328891,
            'image': 'https://artworks.thetvdb.com/banners/v4/series/428456/backgrounds/63bb0b983ef82.jpg',
            'includesText': False,
            'language': None,
            'score': 100001,
            'status': { 'id': 0, 'name': None },
            'tagOptions': None,
            'thumbnail': 'https://artworks.thetvdb.com/banners/v4/series/428456/backgrounds/63bb0b983ef82_t.jpg',
            'thumbnailHeight': 0,
            'thumbnailWidth': 0,
            'type': 3,
            'updatedAt': 0,
            'width': 1920
        },
        {
            'height': 1000,
            'id': 63304540,
            'image': 'https://artworks.thetvdb.com/banners/v4/series/428456/posters/63a19dfc9944f.jpg',
            'includesText': False,
            'language': None,
            'score': 100001,
            'status': { 'id': 0, 'name': None },
            'tagOptions': None,
            'thumbnail': 'https://artworks.thetvdb.com/banners/v4/series/428456/posters/63a19dfc9944f_t.jpg',
            'thumbnailHeight': 0,
            'thumbnailWidth': 0,
            'type': 2,
            'updatedAt': 0,
            'width': 680
        },
        {
            'height': 1080,
            'id': 63534777,
            'image': 'https://artworks.thetvdb.com/banners/v4/series/428456/backgrounds/648d8b64f28c3.jpg',
            'includesText': True,
            'language': 'jpn',
            'score': 100000,
            'status': { 'id': 0, 'name': None },
            'tagOptions': None,
            'thumbnail': 'https://artworks.thetvdb.com/banners/v4/series/428456/backgrounds/648d8b64f28c3_t.jpg',
            'thumbnailHeight': 0,
            'thumbnailWidth': 0,
            'type': 3,
            'updatedAt': 0,
            'width': 1920
        },
        {
            'height': 1080,
            'id': 64192508,
            'image': 'https://artworks.thetvdb.com/banners/v4/series/428456/backgrounds/6763e255787e7.jpg',
            'includesText': False,
            'language': None,
            'score': 100000,
            'status': { 'id': 0, 'name': None },
            'tagOptions': None,
            'thumbnail': 'https://artworks.thetvdb.com/banners/v4/series/428456/backgrounds/6763e255787e7_t.jpg',
            'thumbnailHeight': 0,
            'thumbnailWidth': 0,
            'type': 3,
            'updatedAt': 0,
            'width': 1920
        },
        {
            'height': 1000,
            'id': 63534780,
            'image': 'https://artworks.thetvdb.com/banners/v4/series/428456/posters/648d8ba327bb5.jpg',
            'includesText': True,
            'language': 'jpn',
            'score': 100000,
            'status': { 'id': 0, 'name': None },
            'tagOptions': None,
            'thumbnail': 'https://artworks.thetvdb.com/banners/v4/series/428456/posters/648d8ba327bb5_t.jpg',
            'thumbnailHeight': 0,
            'thumbnailWidth': 0,
            'type': 2,
            'updatedAt': 0,
            'width': 680
        },
        {
            'height': 310,
            'id': 63338301,
            'image': 'https://artworks.thetvdb.com/banners/v4/series/428456/clearlogo/63c42e2078023.png',
            'includesText': True,
            'language': 'jpn',
            'score': 100000,
            'status': { 'id': 0, 'name': None },
            'tagOptions': None,
            'thumbnail': 'https://artworks.thetvdb.com/banners/v4/series/428456/clearlogo/63c42e2078023_t.png',
            'thumbnailHeight': 0,
            'thumbnailWidth': 0,
            'type': 23,
            'updatedAt': 0,
            'width': 800
        },
        {
            'height': 140,
            'id': 63952875,
            'image': 'https://artworks.thetvdb.com/banners/v4/series/428456/banners/663d6e502b0bc.jpg',
            'includesText': True,
            'language': 'jpn',
            'score': 100000,
            'status': { 'id': 0, 'name': None },
            'tagOptions': None,
            'thumbnail': 'https://artworks.thetvdb.com/banners/v4/series/428456/banners/663d6e502b0bc_t.jpg',
            'thumbnailHeight': 0,
            'thumbnailWidth': 0,
            'type': 1,
            'updatedAt': 0,
            'width': 758
        },
        {
            'height': 1000,
            'id': 63599231,
            'image': 'https://artworks.thetvdb.com/banners/v4/series/428456/posters/64cd0db7ddd1c.jpg',
            'includesText': True,
            'language': 'eng',
            'score': 1,
            'status': { 'id': 0, 'name': None },
            'tagOptions': None,
            'thumbnail': 'https://artworks.thetvdb.com/banners/v4/series/428456/posters/64cd0db7ddd1c_t.jpg',
            'thumbnailHeight': 0,
            'thumbnailWidth': 0,
            'type': 2,
            'updatedAt': 0,
            'width': 680
        },
        {
            'height': 1000,
            'id': 63780284,
            'image': 'https://artworks.thetvdb.com/banners/v4/series/428456/posters/6590392998822.jpg',
            'includesText': True,
            'language': 'eng',
            'score': 0,
            'status': { 'id': 0, 'name': None },
            'tagOptions': None,
            'thumbnail': 'https://artworks.thetvdb.com/banners/v4/series/428456/posters/6590392998822_t.jpg',
            'thumbnailHeight': 0,
            'thumbnailWidth': 0,
            'type': 2,
            'updatedAt': 0,
            'width': 680
        },
        {
            'height': 1000,
            'id': 63582968,
            'image': 'https://artworks.thetvdb.com/banners/v4/series/428456/posters/64be8ee784c43.jpg',
            'includesText': True,
            'language': 'pt',
            'score': 0,
            'status': { 'id': 0, 'name': None },
            'tagOptions': None,
            'thumbnail': 'https://artworks.thetvdb.com/banners/v4/series/428456/posters/64be8ee784c43_t.jpg',
            'thumbnailHeight': 0,
            'thumbnailWidth': 0,
            'type': 2,
            'updatedAt': 0,
            'width': 680
        }],
        'averageRuntime': 25,
        'characters': [{
            'aliases': None,
            'episodeId': None,
            'id': 68857398,
            'image': 'https://artworks.thetvdb.com/banners/v4/actor/8017722/photo/63bb74f6b5307.jpg',
            'isFeatured': True,
            'movie': None,
            'movieId': None,
            'name': 'Ash Ketchum',
            'nameTranslations': None,
            'overviewTranslations': None,
            'peopleId': 8017722,
            'peopleType': 'Actor',
            'personImgURL': 'https://artworks.thetvdb.com/banners/person/8017722/primary.jpg',
            'personName': 'Rika Matsumoto',
            'series': None,
            'seriesId': 428456,
            'sort': 0,
            'tagOptions': None,
            'type': 3,
            'url': 'https://thetvdb.com/people/8017722-rika-matsumoto'
        },
        {
            'aliases': None,
            'episodeId': None,
            'id': 68857399,
            'image': 'https://artworks.thetvdb.com/banners/v4/actor/343238/photo/63bb764e668da.jpg',
            'isFeatured': True,
            'movie': None,
            'movieId': None,
            'name': 'Misty',
            'nameTranslations': None,
            'overviewTranslations': None,
            'peopleId': 343238,
            'peopleType': 'Actor',
            'personImgURL': 'https://artworks.thetvdb.com/banners/person/343238/61b5c44934af2.jpg',
            'personName': 'Mayumi Iizuka',
            'series': None,
            'seriesId': 428456,
            'sort': 0,
            'tagOptions': None,
            'type': 3,
            'url': 'https://thetvdb.com/people/343238-mayumi-iizuka'
        },
        {
            'aliases': None,
            'episodeId': None,
            'id': 68857401,
            'image': 'https://artworks.thetvdb.com/banners/v4/actor/279183/photo/63bb7725616f0.jpg',
            'isFeatured': True,
            'movie': None,
            'movieId': None,
            'name': 'Brock',
            'nameTranslations': None,
            'overviewTranslations': None,
            'peopleId': 279183,
            'peopleType': 'Actor',
            'personImgURL': 'https://artworks.thetvdb.com/banners/person/279183/primary.jpg',
            'personName': 'Yuuji Ueda',
            'series': None,
            'seriesId': 428456,
            'sort': 0,
            'tagOptions': None,
            'type': 3,
            'url': 'https://thetvdb.com/people/279183-yuuji-ueda'
        },
        {
            'aliases': None,
            'episodeId': None,
            'id': 68860734,
            'image': None,
            'isFeatured': False,
            'movie': None,
            'movieId': None,
            'name': None,
            'nameTranslations': None,
            'overviewTranslations': None,
            'peopleId': 543087,
            'peopleType': 'Director',
            'personImgURL': None,
            'personName': 'Daiki Tomiyasu',
            'series': None,
            'seriesId': 428456,
            'sort': 0,
            'tagOptions': None,
            'type': 1,
            'url': 'https://thetvdb.com/people/543087-daiki-tomiyasu'
        },
        {
            'aliases': None,
            'episodeId': None,
            'id': 68865986,
            'image': 'https://artworks.thetvdb.com/banners/v4/actor/292480/photo/63cadce639767.jpg',
            'isFeatured': False,
            'movie': None,
            'movieId': None,
            'name': 'Cilan',
            'nameTranslations': None,
            'overviewTranslations': None,
            'peopleId': 292480,
            'peopleType': 'Actor',
            'personImgURL': 'https://artworks.thetvdb.com/banners/person/292480/61f9414b80f68.jpg',
            'personName': 'Mamoru Miyano',
            'series': None,
            'seriesId': 428456,
            'sort': 1,
            'tagOptions': None,
            'type': 3,
            'url': 'https://thetvdb.com/people/292480-mamoru-miyano'
        },
        {
            'aliases': None,
            'episodeId': None,
            'id': 68865987,
            'image': 'https://artworks.thetvdb.com/banners/v4/actor/282368/photo/63cadd6aa9ee2.jpg',
            'isFeatured': False,
            'movie': None,
            'movieId': None,
            'name': 'Jessie',
            'nameTranslations': None,
            'overviewTranslations': None,
            'peopleId': 282368,
            'peopleType': 'Actor',
            'personImgURL': 'https://artworks.thetvdb.com/banners/person/282368/61be2cb675f8d.jpg',
            'personName': 'Megumi Hayashibara',
            'series': None,
            'seriesId': 428456,
            'sort': 2,
            'tagOptions': None,
            'type': 3,
            'url': 'https://thetvdb.com/people/282368-megumi-hayashibara'
        },
        {
            'aliases': None,
            'episodeId': None,
            'id': 68865988,
            'image': 'https://artworks.thetvdb.com/banners/v4/actor/7874486/photo/63caddcd8bb1b.jpg',
            'isFeatured': False,
            'movie': None,
            'movieId': None,
            'name': 'James',
            'nameTranslations': None,
            'overviewTranslations': None,
            'peopleId': 7874486,
            'peopleType': 'Actor',
            'personImgURL': 'https://artworks.thetvdb.com/banners/person/7874486/primary.jpg',
            'personName': "Shin'ichirou Miki",
            'series': None,
            'seriesId': 428456,
            'sort': 3,
            'tagOptions': None,
            'type': 3,
            'url': 'https://thetvdb.com/people/7874486-shinichirou-miki'
        }],
        'companies': [],
        'contentRatings': [],
        'defaultSeasonType': 1,
        'episodes': None,
        'firstAired': '2023-01-13',
        'genres': [{
            'id': 16,
            'name': 'Children',
            'slug': 'children'
        },
        {
            'id': 17,
            'name': 'Animation',
            'slug': 'animation'
        },
        {
            'id': 18,
            'name': 'Adventure',
            'slug': 'adventure'
        },
        { 'id': 27, 'name': 'Anime', 'slug': 'anime' }],
        'id': 428456,
        'image': 'https://artworks.thetvdb.com/banners/v4/series/428456/posters/63a19dfc9944f.jpg',
        'isOrderRandomized': False,
        'lastAired': '2023-03-24',
        'lastUpdated': '2025-02-27 16:23:07',
        'lists': [{
            'aliases': [],
            'id': 6144,
            'image': '',
            'imageIsFallback': False,
            'isOfficial': True,
            'name': 'Pokémon Franchise',
            'nameTranslations': ['deu', 'eng', 'por', 'spa'],
            'overview': 'Ash Ketchum dreams of becoming a '
                                          'Pokémon master. Professor Oak, the '
                                          'local Pokémon researcher, entrusts '
                                          'a Pikachu, the only Pokémon he has '
                                          'left to Ash. Ash does his best to '
                                          'befriend Pikachu, but it refuses to '
                                          'trust him. Only after Ash protects '
                                          'Pikachu from an angry group of '
                                          'Spearows does Pikachu realize how '
                                          'much Ash cares. Along the way, Ash '
                                          'makes many human and Pokémon '
                                          'friends as he works his way through '
                                          "the ranks of the world's many "
                                          'Pokémon Leagues.',
            'overviewTranslations': ['deu', 'eng', 'spa'],
            'remoteIds': None,
            'score': 1487039,
            'tags': None,
            'url': 'pokemon'
        }],
        'name': 'ポケットモンスター めざせポケモンマスター',
        'nameTranslations': ['jpn',
            'eng',
            'zho',
            'pt',
            'spa',
            'ita',
            'pol',
            'deu',
            'rus',
            'fin',
            'nld',
            'fra',
            'kor',
            'por'],
        'nextAired': '',
        'originalCountry': 'jpn',
        'originalLanguage': 'jpn',
        'overview': '放送では、かつて共に旅をしたカスミとタケシのほか、サトシが各地方で強い絆を結びゲットしたポケモンたちが登場。ワクワクと感動がいっぱいの冒険をさらに盛り上げます。',
        'overviewTranslations': ['jpn',
            'eng',
            'zho',
            'pt',
            'ita',
            'pol',
            'rus',
            'fin',
            'nld',
            'fra',
            'por'],
        'remoteIds': [{
            'id': '228369',
            'sourceName': 'TheMovieDB.com',
            'type': 12
        }],
        'score': 3059,
        'seasonTypes': [{
            'alternateName': None,
            'id': 1,
            'name': 'Aired Order',
            'type': 'official'
        },
        {
            'alternateName': None,
            'id': 3,
            'name': 'Absolute Order',
            'type': 'absolute'
        }],
        'seasons': [{
            'companies': {
                'distributor': None,
                'network': None,
                'production': None,
                'special_effects': None,
                'studio': None
            },
            'id': 2035247,
            'lastUpdated': '2023-10-11 10:49:15',
            'nameTranslations': [],
            'number': 0,
            'overviewTranslations': [],
            'seriesId': 428456,
            'type': {
                'alternateName': None,
                'id': 1,
                'name': 'Aired Order',
                'type': 'official'
            }
        },
        {
            'companies': {
                'distributor': None,
                'network': None,
                'production': None,
                'special_effects': None,
                'studio': None
            },
            'id': 2035248,
            'lastUpdated': '2025-02-27 16:22:21',
            'nameTranslations': [],
            'number': 1,
            'overviewTranslations': [],
            'seriesId': 428456,
            'type': {
                'alternateName': None,
                'id': 1,
                'name': 'Aired Order',
                'type': 'official'
            }
        },
        {
            'companies': {
                'distributor': None,
                'network': None,
                'production': None,
                'special_effects': None,
                'studio': None
            },
            'id': 2035249,
            'lastUpdated': '2025-02-27 16:22:22',
            'nameTranslations': [],
            'number': 1,
            'overviewTranslations': [],
            'seriesId': 428456,
            'type': {
                'alternateName': None,
                'id': 3,
                'name': 'Absolute Order',
                'type': 'absolute'
            }
        }],
        'slug': 'pokemon-aim-to-be-a-pokemon-master',
        'status': {
            'id': 2,
            'keepUpdated': False,
            'name': 'Ended',
            'recordType': 'series'
        },
        'tags': None,
        'trailers': [{
            'id': 196892,
            'language': 'jpn',
            'name': 'Trailer',
            'runtime': 0,
            'url': 'https://www.youtube.com/watch?v=ZjiMKr2DYBY'
        }],
        'year': '2023'
    },
    'tvdb_translation': {
        'language': 'eng',
        'name': 'Pokémon: To Be a Pokémon Master',
        'overview': 'Ash, Pikachu and their two friends Misty '
        'and Brock travel around helping Pokémon in '
        'need — all while being watched by a '
        'guardian in the sky.'
    },
    'year': '2023'
}