version: 1
disable_existing_loggers: False

formatters:
  default:
    format: "%(asctime)s %(levelname)-8s %(name)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    style: "%"
  access:
    format: "%(asctime)s %(levelname)-8s %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    style: "%"

handlers:
  console:
    class: logging.StreamHandler
    stream: ext://sys.stderr
    formatter: default

  access_console:
    class: logging.StreamHandler
    stream: ext://sys.stderr
    formatter: access

loggers:
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: False

  uvicorn.error:
    level: INFO
    handlers: [console]
    propagate: False

  uvicorn.access:
    level: INFO
    handlers: [access_console]
    propagate: False

  alembic.runtime.migration:
    level: INFO
    handlers: [console]
    propagate: False

  sqlalchemy.engine:
    level: WARNING
    handlers: [console]
    propagate: False

  watchfiles.main:
    level: WARNING
    handlers: [console]
    propagate: False

root:
  level: INFO
  handlers: [console]
