"""cascade-delete

Revision ID: 1806469f3a64
Revises: a83117fe7e0e
Create Date: 2025-07-18 21:35:01.995690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1806469f3a64'
down_revision: Union[str, None] = 'a83117fe7e0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_constraint("streamable_stream_source_id_fkey", "streamable", type_="foreignkey")
    op.create_foreign_key("streamable_stream_source_id_fkey","streamable","stream_source",["stream_source_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("streamable_schedule_channel_id_fkey", "streamable_schedule", type_="foreignkey")
    op.create_foreign_key("streamable_schedule_channel_id_fkey","streamable_schedule","streamable_channel",["channel_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("video_file_shelf_id_fkey", "video_file", type_="foreignkey")
    op.create_foreign_key("video_file_shelf_id_fkey","video_file","shelf",["shelf_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("movie_tag_tag_id_fkey", "movie_tag", type_="foreignkey")
    op.create_foreign_key("movie_tag_tag_id_fkey","movie_tag","tag",["tag_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("movie_tag_movie_id_fkey", "movie_tag", type_="foreignkey")
    op.create_foreign_key("movie_tag_movie_id_fkey","movie_tag","movie",["movie_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("movie_shelf_shelf_id_fkey", "movie_shelf", type_="foreignkey")
    op.create_foreign_key("movie_shelf_shelf_id_fkey","movie_shelf","shelf",["shelf_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("movie_shelf_movie_id_fkey", "movie_shelf", type_="foreignkey")
    op.create_foreign_key("movie_shelf_movie_id_fkey","movie_shelf","movie",["movie_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("movie_video_file_movie_id_fkey", "movie_video_file", type_="foreignkey")
    op.create_foreign_key("movie_video_file_movie_id_fkey","movie_video_file","movie",["movie_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("movie_video_file_video_file_id_fkey", "movie_video_file", type_="foreignkey")
    op.create_foreign_key("movie_video_file_video_file_id_fkey","movie_video_file","video_file",["video_file_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("show_shelf_shelf_id_fkey", "show_shelf", type_="foreignkey")
    op.create_foreign_key("show_shelf_shelf_id_fkey","show_shelf","shelf",["shelf_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("show_shelf_show_id_fkey", "show_shelf", type_="foreignkey")
    op.create_foreign_key("show_shelf_show_id_fkey","show_shelf","show",["show_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("show_tag_tag_id_fkey", "show_tag", type_="foreignkey")
    op.create_foreign_key("show_tag_tag_id_fkey","show_tag","tag",["tag_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("show_tag_show_id_fkey", "show_tag", type_="foreignkey")
    op.create_foreign_key("show_tag_show_id_fkey","show_tag","show",["show_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("show_season_show_id_fkey", "show_season", type_="foreignkey")
    op.create_foreign_key("show_season_show_id_fkey","show_season","show",["show_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("show_season_tag_tag_id_fkey", "show_season_tag", type_="foreignkey")
    op.create_foreign_key("show_season_tag_tag_id_fkey","show_season_tag","tag",["tag_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("show_season_tag_show_season_id_fkey", "show_season_tag", type_="foreignkey")
    op.create_foreign_key("show_season_tag_show_season_id_fkey","show_season_tag","show_season",["show_season_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("show_episode_show_season_id_fkey", "show_episode", type_="foreignkey")
    op.create_foreign_key("show_episode_show_season_id_fkey","show_episode","show_season",["show_season_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("show_episode_tag_tag_id_fkey", "show_episode_tag", type_="foreignkey")
    op.create_foreign_key("show_episode_tag_tag_id_fkey","show_episode_tag","tag",["tag_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("show_episode_tag_show_episode_id_fkey", "show_episode_tag", type_="foreignkey")
    op.create_foreign_key("show_episode_tag_show_episode_id_fkey","show_episode_tag","show_episode",["show_episode_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("show_episode_video_file_show_episode_id_fkey", "show_episode_video_file", type_="foreignkey")
    op.create_foreign_key("show_episode_video_file_show_episode_id_fkey","show_episode_video_file","show_episode",["show_episode_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("show_episode_video_file_video_file_id_fkey", "show_episode_video_file", type_="foreignkey")
    op.create_foreign_key("show_episode_video_file_video_file_id_fkey","show_episode_video_file","video_file",["video_file_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("stream_source_tag_tag_id_fkey", "stream_source_tag", type_="foreignkey")
    op.create_foreign_key("stream_source_tag_tag_id_fkey","stream_source_tag","tag",["tag_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("stream_source_tag_stream_source_id_fkey", "stream_source_tag", type_="foreignkey")
    op.create_foreign_key("stream_source_tag_stream_source_id_fkey","stream_source_tag","stream_source",["stream_source_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("streamable_tag_tag_id_fkey", "streamable_tag", type_="foreignkey")
    op.create_foreign_key("streamable_tag_tag_id_fkey","streamable_tag","tag",["tag_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("streamable_tag_streamable_id_fkey", "streamable_tag", type_="foreignkey")
    op.create_foreign_key("streamable_tag_streamable_id_fkey","streamable_tag","streamable",["streamable_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("image_file_shelf_id_fkey", "image_file", type_="foreignkey")
    op.create_foreign_key("image_file_shelf_id_fkey","image_file","shelf",["shelf_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("movie_image_file_movie_id_fkey", "movie_image_file", type_="foreignkey")
    op.create_foreign_key("movie_image_file_movie_id_fkey","movie_image_file","movie",["movie_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("movie_image_file_image_file_id_fkey", "movie_image_file", type_="foreignkey")
    op.create_foreign_key("movie_image_file_image_file_id_fkey","movie_image_file","image_file",["image_file_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("show_episode_image_file_show_episode_id_fkey", "show_episode_image_file", type_="foreignkey")
    op.create_foreign_key("show_episode_image_file_show_episode_id_fkey","show_episode_image_file","show_episode",["show_episode_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("show_episode_image_file_image_file_id_fkey", "show_episode_image_file", type_="foreignkey")
    op.create_foreign_key("show_episode_image_file_image_file_id_fkey","show_episode_image_file","image_file",["image_file_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("show_season_image_file_show_season_id_fkey", "show_season_image_file", type_="foreignkey")
    op.create_foreign_key("show_season_image_file_show_season_id_fkey","show_season_image_file","show_season",["show_season_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("show_season_image_file_image_file_id_fkey", "show_season_image_file", type_="foreignkey")
    op.create_foreign_key("show_season_image_file_image_file_id_fkey","show_season_image_file","image_file",["image_file_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("show_image_file_show_id_fkey", "show_image_file", type_="foreignkey")
    op.create_foreign_key("show_image_file_show_id_fkey","show_image_file","show",["show_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("show_image_file_image_file_id_fkey", "show_image_file", type_="foreignkey")
    op.create_foreign_key("show_image_file_image_file_id_fkey","show_image_file","image_file",["image_file_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("metadata_file_shelf_id_fkey", "metadata_file", type_="foreignkey")
    op.create_foreign_key("metadata_file_shelf_id_fkey","metadata_file","shelf",["shelf_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("movie_metadata_file_movie_id_fkey", "movie_metadata_file", type_="foreignkey")
    op.create_foreign_key("movie_metadata_file_movie_id_fkey","movie_metadata_file","movie",["movie_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("movie_metadata_file_metadata_file_id_fkey", "movie_metadata_file", type_="foreignkey")
    op.create_foreign_key("movie_metadata_file_metadata_file_id_fkey","movie_metadata_file","metadata_file",["metadata_file_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("show_episode_metadata_file_show_episode_id_fkey", "show_episode_metadata_file", type_="foreignkey")
    op.create_foreign_key("show_episode_metadata_file_show_episode_id_fkey","show_episode_metadata_file","show_episode",["show_episode_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("show_episode_metadata_file_metadata_file_id_fkey", "show_episode_metadata_file", type_="foreignkey")
    op.create_foreign_key("show_episode_metadata_file_metadata_file_id_fkey","show_episode_metadata_file","metadata_file",["metadata_file_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("show_season_metadata_file_show_season_id_fkey", "show_season_metadata_file", type_="foreignkey")
    op.create_foreign_key("show_season_metadata_file_show_season_id_fkey","show_season_metadata_file","show_season",["show_season_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("show_season_metadata_file_metadata_file_id_fkey", "show_season_metadata_file", type_="foreignkey")
    op.create_foreign_key("show_season_metadata_file_metadata_file_id_fkey","show_season_metadata_file","metadata_file",["metadata_file_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("show_metadata_file_show_id_fkey", "show_metadata_file", type_="foreignkey")
    op.create_foreign_key("show_metadata_file_show_id_fkey","show_metadata_file","show",["show_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("show_metadata_file_metadata_file_id_fkey", "show_metadata_file", type_="foreignkey")
    op.create_foreign_key("show_metadata_file_metadata_file_id_fkey","show_metadata_file","metadata_file",["metadata_file_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("user_tag_user_id_fkey", "user_tag", type_="foreignkey")
    op.create_foreign_key("user_tag_user_id_fkey","user_tag","snowstream_user",["user_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("user_tag_tag_id_fkey", "user_tag", type_="foreignkey")
    op.create_foreign_key("user_tag_tag_id_fkey","user_tag","tag",["tag_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("user_shelf_user_id_fkey", "user_shelf", type_="foreignkey")
    op.create_foreign_key("user_shelf_user_id_fkey","user_shelf","snowstream_user",["user_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("user_shelf_shelf_id_fkey", "user_shelf", type_="foreignkey")
    op.create_foreign_key("user_shelf_shelf_id_fkey","user_shelf","shelf",["shelf_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("user_stream_source_user_id_fkey", "user_stream_source", type_="foreignkey")
    op.create_foreign_key("user_stream_source_user_id_fkey","user_stream_source","snowstream_user",["user_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("user_stream_source_stream_source_id_fkey", "user_stream_source", type_="foreignkey")
    op.create_foreign_key("user_stream_source_stream_source_id_fkey","user_stream_source","stream_source",["stream_source_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("client_device_user_client_device_id_fkey", "client_device_user", type_="foreignkey")
    op.create_foreign_key("client_device_user_client_device_id_fkey","client_device_user","client_device",["client_device_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("client_device_user_user_id_fkey", "client_device_user", type_="foreignkey")
    op.create_foreign_key("client_device_user_user_id_fkey","client_device_user","snowstream_user",["user_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("watch_progress_client_device_user_id_fkey", "watch_progress", type_="foreignkey")
    op.create_foreign_key("watch_progress_client_device_user_id_fkey","watch_progress","client_device_user",["client_device_user_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("watch_progress_movie_id_fkey", "watch_progress", type_="foreignkey")
    op.create_foreign_key("watch_progress_movie_id_fkey","watch_progress","movie",["movie_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("watch_progress_show_episode_id_fkey", "watch_progress", type_="foreignkey")
    op.create_foreign_key("watch_progress_show_episode_id_fkey","watch_progress","show_episode",["show_episode_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("watch_progress_streamable_id_fkey", "watch_progress", type_="foreignkey")
    op.create_foreign_key("watch_progress_streamable_id_fkey","watch_progress","streamable",["streamable_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("watch_count_client_device_user_id_fkey", "watch_count", type_="foreignkey")
    op.create_foreign_key("watch_count_client_device_user_id_fkey","watch_count","client_device_user",["client_device_user_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("watch_count_movie_id_fkey", "watch_count", type_="foreignkey")
    op.create_foreign_key("watch_count_movie_id_fkey","watch_count","movie",["movie_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("watch_count_show_episode_id_fkey", "watch_count", type_="foreignkey")
    op.create_foreign_key("watch_count_show_episode_id_fkey","watch_count","show_episode",["show_episode_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("watch_count_streamable_id_fkey", "watch_count", type_="foreignkey")
    op.create_foreign_key("watch_count_streamable_id_fkey","watch_count","streamable",["streamable_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("watched_client_device_user_id_fkey", "watched", type_="foreignkey")
    op.create_foreign_key("watched_client_device_user_id_fkey","watched","client_device_user",["client_device_user_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("watched_movie_id_fkey", "watched", type_="foreignkey")
    op.create_foreign_key("watched_movie_id_fkey","watched","movie",["movie_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("watched_show_episode_id_fkey", "watched", type_="foreignkey")
    op.create_foreign_key("watched_show_episode_id_fkey","watched","show_episode",["show_episode_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("watched_streamable_id_fkey", "watched", type_="foreignkey")
    op.create_foreign_key("watched_streamable_id_fkey","watched","streamable",["streamable_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("transcode_session_client_device_user_id_fkey", "transcode_session", type_="foreignkey")
    op.create_foreign_key("transcode_session_client_device_user_id_fkey","transcode_session","client_device_user",["client_device_user_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("transcode_session_video_file_id_fkey", "transcode_session", type_="foreignkey")
    op.create_foreign_key("transcode_session_video_file_id_fkey","transcode_session","video_file",["video_file_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("transcode_session_streamable_id_fkey", "transcode_session", type_="foreignkey")
    op.create_foreign_key("transcode_session_streamable_id_fkey","transcode_session","streamable",["streamable_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("playing_queue_client_device_user_id_fkey", "playing_queue", type_="foreignkey")
    op.create_foreign_key("playing_queue_client_device_user_id_fkey","playing_queue","client_device_user",["client_device_user_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("keepsake_shelf_shelf_id_fkey", "keepsake_shelf", type_="foreignkey")
    op.create_foreign_key("keepsake_shelf_shelf_id_fkey","keepsake_shelf","shelf",["shelf_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("keepsake_shelf_keepsake_id_fkey", "keepsake_shelf", type_="foreignkey")
    op.create_foreign_key("keepsake_shelf_keepsake_id_fkey","keepsake_shelf","keepsake",["keepsake_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("keepsake_video_file_keepsake_id_fkey", "keepsake_video_file", type_="foreignkey")
    op.create_foreign_key("keepsake_video_file_keepsake_id_fkey","keepsake_video_file","keepsake",["keepsake_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("keepsake_video_file_video_file_id_fkey", "keepsake_video_file", type_="foreignkey")
    op.create_foreign_key("keepsake_video_file_video_file_id_fkey","keepsake_video_file","video_file",["video_file_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("keepsake_image_file_keepsake_id_fkey", "keepsake_image_file", type_="foreignkey")
    op.create_foreign_key("keepsake_image_file_keepsake_id_fkey","keepsake_image_file","keepsake",["keepsake_id"],["id"],ondelete="CASCADE")
    op.drop_constraint("keepsake_image_file_image_file_id_fkey", "keepsake_image_file", type_="foreignkey")
    op.create_foreign_key("keepsake_image_file_image_file_id_fkey","keepsake_image_file","image_file",["image_file_id"],["id"],ondelete="CASCADE")


def downgrade() -> None:
    pass
