{
    'air_date': '2020-03-26',
        'crew': [{
            'adult': False,
            'credit_id': '61b09e35da9ef20043e9642f',
            'department': 'Writing',
            'gender': 2,
            'id': 1482514,
            'job': 'Writer',
            'jobs': None,
            'known_for_department': 'Directing',
            'name': 'Joe Brumm',
            'order': None,
            'original_name': 'Joe Brumm',
            'popularity': 0.4117,
            'profile_path': '/lI6AoQnS9eLH5LjXL6GSy8VGPfv.jpg',
            'total_episode_count': None
        },
        {
            'adult': False,
            'credit_id': '61be91c8105611001cca42c2',
            'department': 'Sound',
            'gender': 0,
            'id': 2494826,
            'job': 'Music',
            'jobs': None,
            'known_for_department': 'Sound',
            'name': 'Joff Bush',
            'order': None,
            'original_name': 'Joff Bush',
            'popularity': 0.2424,
            'profile_path': '/q3QeZGFbqjmglO0ceKOXH9oKA0q.jpg',
            'total_episode_count': None
        },
        {
            'adult': False,
            'credit_id': '65a509772d1e400125cdc442',
            'department': 'Art',
            'gender': 0,
            'id': 3351879,
            'job': 'Storyboard Artist',
            'jobs': None,
            'known_for_department': 'Acting',
            'name': 'Jasmine Moody',
            'order': None,
            'original_name': 'Jasmine Moody',
            'popularity': 0.0168,
            'profile_path': None,
            'total_episode_count': None
        }],
            'episode_number': 10,
                'guest_stars': [{
                    'adult': False,
                    'cast_id': None,
                    'character': 'Pat (voice)',
                    'credit_id': '61be8a1b0143250043332384',
                    'gender': 2,
                    'id': 3351788,
                    'known_for_department': 'Acting',
                    'name': 'Brad Elliott',
                    'order': 574,
                    'original_name': 'Brad Elliott',
                    'popularity': 0.1796,
                    'profile_path': None,
                    'roles': None,
                    'total_episode_count': None
                }],
                    'id': 2194072,
                        'name': 'Rug Island',
                            'order': None,
                                'overview': "On Bingo and Bluey's Rug Island, a pack of felt pens can be "
    'anything - bananas, campfires, even a snake! But Dad will need '
    'to embrace his inner kid if he wants to make it his home.',
        'production_code': '',
            'runtime': 7,
                'season_number': 2,
                    'show_id': 82728,
                        'still_path': '/wHEwbJCrQYlxiYg1ugT7RCms8yf.jpg',
                            'still_url': 'https://image.tmdb.org/t/p/original/wHEwbJCrQYlxiYg1ugT7RCms8yf.jpg',
                                'vote_average': 7.0,
                                    'vote_count': 3
}
