{'adult': False,
 'alternative_titles': None,
 'backdrop_path': '/bfh9Z3Ghz4FOJAfLOAhmc3ccnHU.jpg',
 'belongs_to_collection': {'backdrop_path': '/kmEsQL2vOTA0jnM28fXS45Ky8kX.jpg',
                           'id': 1241,
                           'name': 'Harry Potter Collection',
                           'overview': None,
                           'parts': None,
                           'poster_path': '/s4hXqX1VyWMc2ctJRuNBDB7YNJ3.jpg'},
 'budget': 125000000,
 'credits': None,
 'external_ids': None,
 'genre_ids': None,
 'genres': [{'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}],
 'homepage': 'https://www.warnerbros.com/movies/harry-potter-and-sorcerers-stone/',
 'id': 671,
 'images': None,
 'imdb_id': 'tt0241527',
 'keywords': None,
 'media_type': 'movie',
 'original_language': 'en',
 'original_title': "Harry Potter and the Philosopher's Stone",
 'overview': "Harry Potter has lived under the stairs at his aunt and uncle's "
             "house his whole life. But on his 11th birthday, he learns he's a "
             'powerful wizard—with a place waiting for him at the Hogwarts '
             'School of Witchcraft and Wizardry. As he learns to harness his '
             "newfound powers with the help of the school's kindly headmaster, "
             "Harry uncovers the truth about his parents' deaths—and about the "
             "villain who's to blame.",
 'popularity': 42.0104,
 'poster_path': '/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg',
 'poster_url': 'https://image.tmdb.org/t/p/original/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg',
 'production_companies': [{'description': None,
                           'headquarters': None,
                           'homepage': None,
                           'id': 174,
                           'logo_path': '/zhD3hhtKB5qyv7ZeL4uLpNxgMVU.png',
                           'name': 'Warner Bros. Pictures',
                           'origin_country': 'US',
                           'parent_company': None},
                          {'description': None,
                           'headquarters': None,
                           'homepage': None,
                           'id': 437,
                           'logo_path': '/nu20mtwbEIhUNnQ5NXVhHsNknZj.png',
                           'name': 'Heyday Films',
                           'origin_country': 'GB',
                           'parent_company': None},
                          {'description': None,
                           'headquarters': None,
                           'homepage': None,
                           'id': 436,
                           'logo_path': '/A7WCkG3F0NFvjGCwUnclpGdIu9E.png',
                           'name': '1492 Pictures',
                           'origin_country': 'US',
                           'parent_company': None}],
 'production_countries': [{'iso_3166_1': 'GB', 'name': 'United Kingdom'},
                          {'iso_3166_1': 'US',
                           'name': 'United States of America'}],
 'recommendations': None,
 'release_date': '2001-11-16',
 'release_dates': None,
 'revenue': 976475550,
 'reviews': None,
 'runtime': 152,
 'similar': None,
 'spoken_languages': [{'english_name': 'English',
                       'iso_639_1': 'en',
                       'name': 'English'}],
 'status': 'Released',
 'tagline': 'Let the magic begin.',
 'title': "Harry Potter and the Philosopher's Stone",
 'translations': None,
 'video': False,
 'videos': None,
 'vote_average': 7.901,
 'vote_count': 28249,
 'watch_providers': None}
